# 基于生成器的协程
最开始是通过生成器实现协程的。

示例：
```python
def simple_coroutine():
    print('coroutine start')
    x = yield
    print('coroutine recv：', x)


if __name__ == "__main__":
    my_coroutine = simple_coroutine()
    print(my_coroutine)
    next(my_coroutine)
    print(my_coroutine.send(100))
"""
<generator object simple_coroutine at 0x0000022587502570>
coroutine start
coroutine recv： 100
Traceback (most recent call last):
  ...
StopIteration
"""
```
由于生成器并不是一次生成所有元素，而是一次一次的执行返回,需要使用next()激活生成器，send()方法
会像yield发送值，由yield表达式左边接收。

协程有四种状态
```python
GEN_CREATED # 等待开始执行
GEN_RUNNING # 解释器正在执行（只有在多线程应用中才能看到这个状态）
GEN_SUSPENDED # 在yield表达式处暂停
GEN_CLOSED # 执行结束
```

产生多个值示例：
```python
from inspect import getgeneratorstate


def simple_coroutine2(a):
    print('coroutine2 start: a=', a)
    b = yield a
    print('recv: b=', b)
    c = yield a + b
    print("recv: c=", c)


if __name__ == "__main__":
    my_coroutine = simple_coroutine2(14)
    # 此时的协程没有激活，处于GEN_CREATED状态
    print(getgeneratorstate(my_coroutine))

    # 激活协程，next返回值为yield右边表达式返回值
    print(next(my_coroutine))

    # yield产出a的值之后，暂停，等待为b赋值，所以状态是GEN_SUSPENDED
    print(getgeneratorstate(my_coroutine))

    # 把数字28发送给暂停的协程，计算出 a+b的值，协程暂停，等待为b赋值
    print(my_coroutine.send(28))
    
    # 把 数字99发送给暂停的协程，产出c的值，协程终止，抛出StopIteration异常
    print(my_coroutine.send(99))
    
    # 此时协程已经结束，状态应该是GEN_CLOSED状态
    print(getgeneratorstate(my_coroutine))
"""
GEN_CREATED
coroutine2 start: a= 14
14
GEN_SUSPENDED
recv: b= 28
42 
recv: c= 99
Traceback (most recent call last):
  ...
StopIteration
"""
```
在赋值语句中，=右面的代码在赋值之间执行，对于 `b=yield a`这行代码来说，等到客户端
激活协程时才会设定b的值。
## 使用协程计算移动平均值
示例：
```python
def averager():
    total = 0.0
    count = 0
    average = None
    while True:
        term = yield average
        total += term
        count += 1
        average = total / count


if __name__ == "__main__":
    coro_avg = averager()
    
    print(next(coro_avg))
    print(coro_avg.send(10))
    print(coro_avg.send(30))
    print(coro_avg.send(5))
"""
None
10.0
20.0
15.0
"""
```
## 预激协程装饰器
协程在启动之前，需要预激，除了使用next方法，可以使用装饰器，简化激活协程的过程

示例:
```python
from functools import wraps


def coroutine(func):
    @wraps(func)
    def primer(*args, **kwargs):
        gen = func(*args, **kwargs)
        next(gen)
        return gen
    return primer


@coroutine
def averager():
    total = 0.0
    count = 0
    average = None
    while True:
        term = yield average
        total += term
        count += 1
        average = total / count


if __name__ == "__main__":
    coro_avg = averager()
    print(coro_avg.send(10))
    print(coro_avg.send(30))
    print(coro_avg.send(5))
"""
10.0
20.0
15.0
"""
```
## 终止协程和异常处理
有两个方法，可以显示的把异常发送给协程。
- generator.throw()
    
    使生成器在暂停的yield表达式出抛出指定的异常，如果生成器处理了抛出的异常，代码会向前执行到下一个yield表达式，
    而产出的值会成为调用generator.throw方法得到的返回值，如果生成器没有处理异常
    ，异常会向上冒泡，传递到调用方的上下文中。
    
- generator.close()
        
     使生成器在暂停的yield表达式出抛出GeneratorExit的异常。如果生成器没有处理这个异常，或者抛出stopIteration，调用方不会报错。
     如果收到GeneratorExit的异常，生成器一定不能产出值，否则会抛出RuntimeError。生成器抛出的其他异常会向上冒泡，传递给调用方。

示例：
```python
from inspect import getgeneratorstate


class DemoException(Exception):
    pass


def demo_exc_handing():
    print('coroutine start')
    while True:
        try:
            x = yield
        except DemoException:
            print('DemoException handled')
        else:
            print("coroutine recv: {!r}".format(x))

    # 这一行代码永远不会执行，因为只有未处理的异常才会终止无限循环，而出现未处理的异常，协程会立马终止
    raise RuntimeError('this line should never run')


if __name__ == "__main__":
    exc_coro = demo_exc_handing()
    next(exc_coro)
    exc_coro.send(11)
    exc_coro.send(22)
    # exc_coro.close()
    # print(getgeneratorstate(exc_coro))

    # 把DemoException异常传入demo_exc_handing协程，他会处理，然后继续执行
    exc_coro.throw(DemoException)
    print(getgeneratorstate(exc_coro))

    # 如果传入未处理的异常，协程会停止
    exc_coro.throw(ZeroDivisionError)
"""
coroutine start
coroutine recv: 11
coroutine recv: 22
DemoException handled
GEN_SUSPENDED
"""
```
## 让协程返回值
示例：
```python
from collections import namedtuple


Result = namedtuple('Result', 'count average')


def averager():
    total = 0.0
    count = 0
    average = None
    while True:
        term = yield
        if term is None:
            break
        total += term
        count += 1
        average = total / count
    return Result(count, average)


if __name__ == "__main__":
    coro_avg = averager()
    next(coro_avg)
    coro_avg.send(10)
    coro_avg.send(30)
    coro_avg.send(6.5)
    # 发送None终止循环，导致协程结束，生成器抛出StopIteration异常，返回结果保存在异常对象value属性中。
    # coro_avg.send(None)
    result = None
    try:
        coro_avg.send(None)
    except StopIteration as e:
        result = e.value
    print(result)
"""
Result(count=3, average=15.5)
"""
```
## yield from
yield form是全新的语言结构，作用比yield作用大很多

yield from 可以简化for循环中的yield表达式

示例：
```python
def gen():
    for c in 'AB':
        yield c
    for i in range(1, 3):
        yield i


def gen1():
    yield from 'AB'
    yield from range(1, 3)


if __name__ == '__main__':
    print(list(gen()))
    print(list(gen1()))
"""
['A', 'B', 1, 2]
['A', 'B', 1, 2]
"""
```
yield from 不止可以代替for循环，主要功能是打开双向通道，把最外层的调用方和最内层
的子生成器连接起来，这样二者可以直接发送和产出值，还可以直接传入异常，这样不用再协程中有大量处理异常的代码。

- 委派生成器：包含yield from <iterable> 表达式生成器函数。
- 子生成器：从yield from 表达式中 <iterable>部分获取的生成器。
- 调用方：调用委派生成器的客户端代码。

示例：
```python

from collections import namedtuple


Result = namedtuple('Result', 'count average')


# 子生成器
def averager():
    total = 0.0
    count = 0
    average = None
    while True:
        term = yield
        if term is None:
            break
        total += term
        count += 1
        average = total / count
    return Result(count, average)


# 委派生成器
def grouper(results, key):
    while True:
        results[key] = yield from averager()


# 调用方
def main(data):
    results = {}
    for key, values in data.items():
        # group发送的每个值都会由yield from处理，通过管道传给averager实例。
        group = grouper(results, key)
        next(group)
        for value in values:
            group.send(value)
        # 如果子生成器不终止，委派生成器会在yield from表达式处永远暂停
        group.send(None)
    report(results)


def report(results):
    for key, result in sorted(results.items()):
        group, unit = key.split(';')
        print('{:2} {:5} average {:.2f}{}'.format(result.count, group, result.average, unit))


data = {
    'girls;kg':
        [40.9, 38.5, 44.3, 42.2, 45.2, 41.7, 44.5, 38.0, 40.6, 44.5],
    'girls;m':
        [1.6, 1.51, 1.4, 1.3, 1.41, 1.39, 1.33, 1.46, 1.45, 1.43],
    'boys;kg':
        [39.0, 40.8, 43.2, 40.8, 43.1, 38.6, 41.4, 40.6, 36.3],
    'boys;m':
        [1.38, 1.5, 1.32, 1.25, 1.37, 1.48, 1.25, 1.49, 1.46],
}


if __name__ == '__main__':
    main(data)

"""
 9 boys  average 40.42kg
 9 boys  average 1.39m
10 girls average 42.04kg
10 girls average 1.43m
"""
```
pep380中阐述了yield from的行为

- 子生成器产生的值直接传给委派生成器的调用方
- 使用send方法发给委派生成器的值都会直接传给子生成器。如果发送的是None值，那么会
调用子生成器的__next__方法。如果发送的值不是None，那么会调用子生成器的send方法。
如果调用的方法抛出stopIteration异常，那么委派生成器恢复运行，任何其他异常都会向上冒泡，传给委派生成器。
- 生成器退出时，生成器中的return expr表达式会触发stopIteration异常抛出
- yield from表达式的值是子生成器终止时传给stopIteration异常的第一个参数。
- 除了GeneratorExit 异常外的其他抛给委派生产器的异常，将会被传递到迭代器的throw()方法。如果迭代器throw()调用产生了StopIteration异常，委派生产器恢复并继续执行，其他异常则传递给委派生产器。
- 如果GeneratorExit异常被抛给委派生产器，或者委派生产器的close()方法被调用，如果迭代器有close()的话也将被调用。如果close()调用产生异常，异常将传递给委派生产器。否则，委派生产器将抛出GeneratorExit 异常。

# asyncio
asyncio是Python中的异步编程标准化。
## asyncio中重要的组件
- 事件循环：asyncio模块中，每一个进程都有一个事件循环。把一些函数注册到事件循环上，当满足事件发生的时候，调用相应的协程函数；
- 协程：子程序的泛化概念，可以在执行期间暂停，等待外部的处理完成之后，从之前暂停的地方回复执行。理解为一个使用async关键字定义的函数。 它的调用不会立即执行，而是会返回一个协程对象，协程对象需要注册到事件循环，由事件循环调用 ；
- Futures：定义Future对象，表示尚未完成的计算；
- Tasks： 用于封装和管理并行模式下的协程；协程对象是一个可以挂起的函数，任务则是对协程进一步封装，其中包含任务的各种状态；
- async/await关键字 ：定义协程的关键字，async定义一个协程，await用于挂起阻塞的异步调用接口。

### asyncio工作流程：
- 定义协程对象
- 把协程对象转换为Task任务
- 定义事件循环对象容器
- 把task任务扔进事件循环对象中触发。
示例：
```python
import asyncio


async def hello(name):
    print('hello ', name)


# 定义协程对象
coroutine = hello('world')

# 定义事件循环
loop = asyncio.get_event_loop()
# 转换为task
task = loop.create_task(coroutine)

# task 任务加入到事件循环
loop.run_until_complete(task)
```
### 事件循环

在计算系统中，可以产生事件的实体叫做事件源，能处理事件的实体叫做事件处理者。此外，还有一些第三方实体叫做事件循环。它的作用是管理所有的事件，在整个程序运行过程中不断循环执行，追踪事件发生的顺序将它们放到队列中，当主线程空闲的时候，调用相应的事件处理者处理事件。


事件循环的作用是管理所有的事件，在整个程序运行过程中不断循环执行，追踪事件发生的顺序将它们放到队列中，当主线程空闲的时候，调用相应的事件处理者处理事件。

示例：
```python
import asyncio


# async关键字定义一个协程
async def hello(name):
    print('hello ', name)


# 协程的调用不会直接执行，而是返回一个协程对象
coroutine = hello('world')

# 定义事件循环
loop = asyncio.get_event_loop()
# 转换为task
task = loop.create_task(coroutine)

# task 任务加入到事件循环
"""
协程对象不能直接运行，在注册事件循环时， run_until_complete 将协程包装成了一个 task 。 
task 对象是 Future 类的子类，保存了协程运行后的状态，用于未来获取协程的结果。
"""
loop.run_until_complete(task)
```
### task
run_until_complete 参数是一个 future对象,如果传入的是协程对象，会自动封装成task，task是
future的子类。

task保存了协程运行后的状态，用于未来获取协程的结果。

这两种方法都可以创建task
- loop.create_task(coroutine)
- asyncio.ensure_future(coroutine)

示例：
```python
...


# 定义事件循环
loop = asyncio.get_event_loop()
# 转换为task
task = loop.create_task(coroutine)
print(task)
loop.run_until_complete(task)
print(task)

"""
<Task pending coro=<hello() running at ...>>
hello  world
<Task finished coro=<hello() done, defined at ...> result=None>
"""
```
创建task后，task在加入事件循环之前是pending状态

绑定回调，在task执行完毕的时候可以获取执行的结果，回调的最后一个参数是future对象，通过该对象可以获取协程返回值。如果回调需要多个参数，可以通过偏函数导入。

示例：
```python
import asyncio


async def do_something(x):
    print('waiting: ', x)
    return "done after {}s".format(x)


def callback(future):
    print('callback,', future.result())


coroutine = do_something(2)

loop = asyncio.get_event_loop()

task = asyncio.ensure_future(coroutine)

# 绑定回调函数，在task执行完毕后获取结果
task.add_done_callback(callback)

loop.run_until_complete(task)
"""
waiting:  2
callback, done after 2s
"""
```
callback中没有传入future对象，实际上和创建的task是同一个对象。
### async和await
使用async可以定义协程对象，使用await可以针对耗时的操作进行挂起，就像生成器里的yield一样，函数让出控制权。协程遇到await，事件循环将会挂起该协程，执行别的协程，直到其他的协程也挂起或者执行完毕，再进行下一个协程的执行

示例：
```python
import asyncio


async def do_something(x):
    print('Waiting: ', x)
    await asyncio.sleep(x)
    return 'Done after {}s'.format(x)


coroutine = do_something(2)
loop = asyncio.get_event_loop()
task = asyncio.ensure_future(coroutine)
loop.run_until_complete(task)
print(task.result())
```
在sleep时，使用await让出控制权。即当遇到阻塞调用的函数的时候，使用await方法将协程的控制权让出。以便loop调用其他的协程。
## asyncio并发
asyncio实现并发，就需要多个协程来完成任务，每当有任务阻塞的时候就await，然后其他协程继续工作。

创建多个协程
```python
import asyncio


async def do_something(x):
    print('Waiting:', x)
    await asyncio.sleep(x)
    return "done after {}s".format(x)

coroutine1 = do_something(1)
coroutine2 = do_something(2)
coroutine3 = do_something(4)
loop = asyncio.get_event_loop()
tasks = [asyncio.ensure_future(coroutine1), asyncio.ensure_future(coroutine2), asyncio.ensure_future(coroutine3)]

```
把task注册到事件循环

有两种方法：
- asyncio.wait()
```python
loop = asyncio.get_event_loop()
loop.run_until_complete(asyncio.wait(tasks))
```
- asyncio.gather(coroutine)
```python
loop = asyncio.get_event_loop()
loop.run_until_complete(asyncio.gather(*tasks))
```
两种方法都可以实现注册任务到事件循环，两者区别如下：
- 接受参数方式：wait接受的参数是一个集合，存放多个task。gather以(cro1, cro2, cro3, cro4…)的方式接受协程
- 返回结果不同：wait返回已完成的任务(dones)和未完成的任务(pendings)。gather直接返回。
- 其他： gather可以给任务分组；wait可以控制任务。
完整demo:
```python
import asyncio
import time


async def do_something(x):
    print('Waiting:', x)
    await asyncio.sleep(x)
    return "done after {}s".format(x)


start = time.time()

coroutine1 = do_something(1)
coroutine2 = do_something(2)
coroutine3 = do_something(4)
loop = asyncio.get_event_loop()
tasks = [asyncio.ensure_future(coroutine1), asyncio.ensure_future(coroutine2), asyncio.ensure_future(coroutine3)]

loop.run_until_complete(asyncio.wait(tasks))
end = time.time()

for task in tasks:
    print(task.result())

print('total time:', end - start)

"""
Waiting: 1
Waiting: 2
Waiting: 4
done after 1s
done after 2s
done after 4s
total time: 4.003442764282227
"""
```
总时间为4s左右。4s的阻塞时间，足够前面两个协程执行完毕。如果是同步顺序的任务，那么至少需要7s
### 协程中的嵌套
一个协程中await了另外一个协程，如此连接起来

示例：
```python

import asyncio


# 内部协程
async def do_something(x):
    print('Waiting:', x)
    await asyncio.sleep(x)
    return "done after {}s".format(x)


# 外部协程

async def main():
    coroutine1 = do_something(1)
    coroutine2 = do_something(2)
    coroutine3 = do_something(4)
    tasks = [asyncio.ensure_future(coroutine1), asyncio.ensure_future(coroutine2), asyncio.ensure_future(coroutine3)]
    results = await asyncio.gather(*tasks)
    for result in results:
        print('Task ret: ', result)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
"""
Waiting: 1
Waiting: 2
Waiting: 4
Task ret:  done after 1s
Task ret:  done after 2s
Task ret:  done after 4s
"""
```
### 协程状态
future对象有四种状态
```python
Pending：创建future，还未执行
Running：事件循环正在调用执行任务
Done：任务执行完毕
Cancelled：Task被取消后的状态
```
示例:
```python
import asyncio
import threading
import time


async def do_something(x):
    print('Waiting:', x)
    await asyncio.sleep(x)
    return "done after {}s".format(x)


if __name__ == '__main__':
    coroutine = do_something(2)
    loop = asyncio.get_event_loop()
    task = asyncio.ensure_future(coroutine)

    print("pending状态： ", task)

    try:
        t = threading.Thread(target=loop.run_until_complete, args=(task,))
        t.start()
        time.sleep(1)
        print("running状态： ", task)
        t.join()
    except KeyboardInterrupt as e:
        task.cancel()
        print("cancel状态： ", task)
    finally:
        print("finished状态： ", task)
```